### PR TITLE
record /diagnostics rosbags

### PR DESCRIPTION
**Pull request by ClintLiddick**
record data now published by https://github.com/personalrobotics/barrett_ros_control/pull/17

### CODE REVIEW

**Comment by mkoval** [comment]
We'll have to remember to periodically clean out `/home/herb_home/logs/diagnostics`. Do you plan to automate this somehow or just do manually? Any idea how fast this will grow?

**Comment by ClintLiddick** [comment]
4 minutes generated ~20KB, so ~7-8GB per day? Yeah, I'd better setup a cron script or something in saltstack.

**Comment by mkoval** [comment]
Lets hold off on merging until then - HERB doesn't have that much space on his SSDs, so this could become an issue relatively quickly.

**Comment by mkoval** [comment]
We've had this running for a while, so I'll go ahead and merge this. The bags haven't been an issue yet.

**Pull request merged**
