### PR TITLE
herb upgrade

### PR DESCRIPTION
**Pull request by ClintLiddick**
- Changed `kinect2_bridge.launch` to match new topics in code-iai/iai_kinect2@42787f9bdd7ac04668f8ff85f3209059fca085d2
- Changed `start_herb.sh` to check which host it's being run on, and source appropriate ROS setup file

### CODE REVIEW

**Comment by mkoval** [comment]
If possible, can you replace `kinect2_bridge` with an `<include/>` to the version shipped with `iai_kinect2`?

It's mostly just a matter of setting some `<arg>`'s to `head`. There are some other subtle changes, but I'm not sure these are intentional or an artifact of using an old version of the launch file. (Which reinforces why it's a bad idea to copy it into `herb_launch` in the first place.)

**Comment by ClintLiddick** [comment]
The only thing I can't see how to do via the provided args is set the published topics to `/head/xyz`, since the base itself can't be `head/something`. I guess if we're going to make that change now is the time since all the topics changed anyway. I agree that copying the launch file isn't a great idea.

**Comment by mkoval** [comment]
In this case, it seems like you could just put the `<include/>` inside a namespace, e.g.:

``` xml
<include file="package://kinect2_bridge/launch/kinect2_bridge.launch" ns="head"/>
```

If that is too coarse, then you can always individually `<remap/>` the topics in our launch file:

> The `<remap>` tag allows you to pass in name remapping arguments to the ROS node that you are launching in a more structured manner than setting the `args` attribute of a `<node>` directly. **The `<remap>` tag applies to all subsequent declarations in its scope (`<launch>`, `<node>` or `<group>`).**

**Comment by ClintLiddick** [comment]
Oh I see, have our own launch file that just calls theirs. I like it. When I figure out the odom->map issue I'll do that.

**Comment by ClintLiddick** [comment]
@mkoval I'd like to merge this upgrade first since it is working, then create separate issues for re-working localization and and the kinect2_bridge launch file. Let me know if kosher

**Comment by mkoval** [comment]
Ok, if this works, we can fix #7 and #8 in a separate pull request.

**Pull request merged**
