### PR TITLE
Adding launch file for all the chisel related services

### PR DESCRIPTION
**Pull request by jeking04**
This PR adds a launch file that launches all services need to use chisel from prpy.

### CODE REVIEW

**Comment by mkoval** [comment]
Should we add this to `start-herb.sh`?

**Comment by jeking04** [comment]
Its a good question. I was thinking of this as being similar to `vncc` or `tabletop_tools`. Right now we only start those services when we need them for a particular demo. But maybe we should add each to `start-herb.sh`. Or maybe we treat `chisel` like the `apriltags` module, which is included in `start-herb.sh`. Thoughts? @Shushman @mklingen  Are there downsides to just having these services running all the time?

**Comment by mkoval** [comment]
:+1: for starting all three processes by default, unless there is a significant downside to doing so.

Hopefully @mklingen and @Shushman can clue us in.

**Comment by mklingen** [comment]
Yes, there is a significant downside: chisel will be constantly running in the background eating up all your CPU. I'd need to redesign the server so it doesn't do any processing by default until a service call.

**Comment by mkoval** [comment]
That is a major downside even if we only run Chisel during the demo. How difficult is it to make the modification you suggest? Is that something that you or @Shushman could take care of?

I believe Apriltags also constantly runs in the background. It may be worth starting it by default, anyway, if it does not use very much CPU time. @psigen can you confirm?

I believe VNCC runs on-demand, so there is no downside to starting it by default. @Shushman, can you confirm?

**Comment by Shushman** [comment]
I can confirm that the VNCC server is on-demand. It just needs a single depth and RGB image to work, however, and so was easy to do via service calls. I think Chisel has a bunch of other stuff going on in the background. Whether or not it's easy to change that is something I'd need to hear from Matt on.

**Comment by mkoval** [comment]
I created new issues #24 #25 #26 to track the changes to `start-herb.sh`. There's no reason to stall this pull request for those changes.

**Pull request merged**
